# Generated by Django 6.0.3 on 2026-03-16 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={},
        ),
        migrations.RemoveField(
            model_name='contato',
            name='assunto',
        ),
    ]
